### ISSUE TITLE
Tag minor version

### ISSUE THREAD

**Issue by macintoshplus** [KnpLabs/ConsoleServiceProvider#44]
Hi,

I use Symfony 3.4 and the pull request #40 solve a bug. I prefer do not have an `@dev` in the `composer.json` before send new version into production.

Can you release a new minor version? Please.

Thanks in advance and thanks for this good library.

**Comment by GregOriol** [comment]
@skalpa Thanks for pulling the fix, could you release it too?

**Comment by OtezVikentiy** [comment]
@skalpa @GregOriol 
+1
Waiting for release )))

**Comment by skalpa** [comment]
I'll try and do this during this week-end or next week at the latest. I haven't done it yet because there are a few more fixes I'd like to include with the next release.
I really apologize for the delay, I've been quite busy with other projects lately and haven't been able to take care of this one as much as I would like.

**Comment by skalpa** [comment]
I've just tagged v2.2.0 with full compatibility with Symfony v3.4 and v4.0.
